---
'{src,scripts}/**/*.{ts,tsx}':
  - eslint --fix --max-warnings=0
  - prettier --write

'**/*.yml':
  - prettier --write --parser yaml

data/**/*.{md,mdx}:
  - node --experimental-specifier-resolution=node
    --loader ts-node/esm scripts/update-last-edit.ts
